server.port=8081
s3.region=us-east-1
s3.base-service-url=http://localhost:8888
s3.access-key=test
s3.secret-key=test
s3.http-client.max-connections=100
s3.http-client.connection-timeout=5s
s3.http-client.socket-timeout=30s
s3.http-client.connection-acquisition-timeout=10s